 map_loader_node:
  ros__parameters:
    # This path can be overridden by the launch file
    pcd_path: "/root/ros2_ws/vs/my_3d_map.pcd"
    frame_id: "map"
    publish_rate: 1.0  # Hz 

    # ===== PATHS / GOALS =====
    goals:
      pickup:
        x: 2.0
        y: 1.0
        yaw: 1.57

      drop:
        x: -1.5
        y: 3.0
        yaw: 3.14
